"""Fixed async to sync migration issue

Revision ID: 74a45e98e554
Revises: 21f0803f5cfe
Create Date: 2025-02-13 12:17:05.438122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a45e98e554'
down_revision: Union[str, None] = '21f0803f5cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
