"""Reset and Added HRUser model

Revision ID: e676dc009771
Revises: 
Create Date: 2025-02-18 13:08:40.496548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e676dc009771'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               nullable=False,
               existing_server_default=sa.text("'Unknown'::character varying"))
    op.alter_column('hr_users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('hr_users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_hr_users_id'), 'hr_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_users_id'), table_name='hr_users')
    op.alter_column('hr_users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('hr_users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('candidates', 'address',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'Unknown'::character varying"))
    # ### end Alembic commands ###
