name: Deploy Backend to OCI

on:
  push:
    branches:
      - main  # Deploy when main branch is updated

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to OCI Backend with Password
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 141.148.219.190  # Backend OCI instance IP
          username: ubuntu
          password: ${{ secrets.SSH_PASSWORD }}  # Use GitHub Secret for password
          port: 22  # Explicitly specify SSH port
          script: |
            cd /home/ubuntu/backend
            git pull origin main

            # Ensure Python dependencies are installed
            pip install --user -r requirements.txt  

            # Add ~/.local/bin to PATH to find Alembic
            export PATH=$HOME/.local/bin:$PATH  

            # Ensure Alembic is installed
            pip install --user alembic  

            # Securely apply Alembic migrations using GitHub Secrets
            export DATABASE_URL="postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}"
            alembic upgrade head  

            # Restart Gunicorn properly
            sudo systemctl restart gunicorn || sudo systemctl start gunicorn
