name: Deploy Backend to OCI

on:
  push:
    branches:
      - main  # Deploy only when main branch is updated

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to OCI Instance
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 141.148.219.190
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/backend
            git pull origin main
            pip install -r requirements.txt  # Install Python dependencies (if using Flask/Django/FastAPI)
            npm install  # Install dependencies (if using Node.js)
            pm2 restart backend  # Restart the backend service (if using PM2 for Node.js)
            sudo systemctl restart gunicorn  # Restart Gunicorn (if using Flask/Django)
